version: '3.7'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  nestbox:
    image: nginx
    ports:
      - "443"
    volumes:
      - "./etc/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf"
      - "./ssl:/usr/local/share/ssl"
    depends_on:
      - nestbox-auth
      - nestbox-deployd

  nestbox-auth:
    image: "wazopbx/xivo-auth-mock"
    ports:
      - "9497"
    volumes:
      - "./ssl:/usr/local/share/ssl"
    command: /usr/local/bin/mock-xivo-auth.py 9497

  nestbox-deployd:
    image: wazopbx/wazo-deployd-mock
    ports:
      - "9800"
    volumes:
      - ./ssl/auth:/usr/local/share/ssl/deployd
    command: /usr/local/bin/wazo-deployd-mock.py 9800

  auth:
    image: wazopbx/xivo-auth-mock
    ports:
      - "9497"
    volumes:
      - ./ssl:/usr/local/share/ssl
    command: /usr/local/bin/mock-xivo-auth.py 9497

  confd:
    image: wazopbx/xivo-confd-mock
    volumes:
      - ./ssl:/usr/local/share/ssl
    ports:
      - "9486"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  setupd:
    image: "wazo-setupd-test"
    environment:
      XIVO_UUID: "cd030e68-ace9-4ad4-bc4e-13c8dec67898"
    volumes:
      - "../..:/usr/src/wazo-setupd"
      - "./ssl:/usr/local/share/ssl"
      - "./ssl/confd:/usr/share/xivo-certs"
      - "./etc/wazo-setupd/conf.d/50-default-config.yml:/etc/wazo-setupd/conf.d/50-default-config.yml"
      - "webhookd-config:/etc/wazo-webhookd/conf.d"
      - "nestbox-plugin-config:/etc/wazo-nestbox-plugin/conf.d"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.5/site-packages/xivo"
    ports:
      - "9486"  # from confd
      - "9302"

  webhookd:
    image: wazopbx/wazo-webhookd-mock
    ports:
      - "9300"
    volumes:
      - ./ssl/auth:/usr/local/share/ssl/webhookd
      - nestbox-plugin-config:/etc/wazo-nestbox-plugin/conf.d
      - webhookd-config:/etc/wazo-webhookd/conf.d
    command: /usr/local/bin/wazo-webhookd-mock.py 9300

volumes:
  webhookd-config:
  nestbox-plugin-config:
