version: '3.7'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: '${INTEGRATION_TEST_TIMEOUT}'

  nestbox:
    image: nginx
    ports:
      - '443'
    volumes:
      - ./etc/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf:ro
      - ./ssl:/usr/local/share/ssl:ro
    depends_on:
      - nestbox-auth
      - nestbox-deployd

  nestbox-auth:
    image: wazopbx/wazo-auth-mock
    ports:
      - '9497'

  nestbox-deployd:
    image: wazopbx/wazo-deployd-mock
    ports:
      - '9800'
    command: /usr/local/bin/wazo-deployd-mock.py 9800

  auth:
    image: wazopbx/wazo-auth-mock
    ports:
      - '9497'
    volumes:
      - setupd-generated-config:/usr/share/wazo-setupd:ro
      - auth-config:/etc/wazo-auth/conf.d:ro

  confd:
    image: wazopbx/wazo-confd-mock
    ports:
      - '9486'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672'
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  setupd:
    image: wazo-setupd-test
    environment:
      XIVO_UUID: cd030e68-ace9-4ad4-bc4e-13c8dec67898
    volumes:
      - ../..:/usr/src/wazo-setupd:ro
      - ./ssl:/usr/local/share/ssl:ro
      - ./ssl/confd:/usr/share/xivo-certs:ro
      - ./etc/wazo-setupd/conf.d/50-default-config.yml:/etc/wazo-setupd/conf.d/50-default-config.yml:ro
      - auth-config:/etc/wazo-auth/conf.d
      - webhookd-config:/etc/wazo-webhookd/conf.d
      - nestbox-plugin-config:/etc/wazo-nestbox-plugin/conf.d
      - setupd-generated-config:/usr/share/wazo-setupd
      # - '${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.7/site-packages/xivo'
    ports:
      - '9302'

  sysconfd:
    image: wazopbx/xivo-sysconfd-mock
    ports:
      - '8668'

  webhookd:
    image: wazopbx/wazo-webhookd-mock
    ports:
      - '9300'
    volumes:
      - setupd-generated-config:/usr/share/wazo-setupd:ro
      - webhookd-config:/etc/wazo-webhookd/conf.d:ro
    command: /usr/local/bin/wazo-webhookd-mock.py 9300

volumes:
  setupd-generated-config:
  auth-config:
  webhookd-config:
  nestbox-plugin-config:
