version: '3.7'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  nestbox-auth:
    image: "wazopbx/xivo-auth-mock"
    ports:
      - "9497"
    volumes:
      - "./ssl:/usr/local/share/ssl"
    command: /usr/local/bin/mock-xivo-auth.py 9497 /api/auth

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  setupd:
    image: "wazo-setupd-test"
    environment:
      XIVO_UUID: "cd030e68-ace9-4ad4-bc4e-13c8dec67898"
    volumes:
      - "../..:/usr/src/wazo-setupd"
      - "./ssl:/usr/local/share/ssl"
      - "./etc/wazo-setupd/conf.d/50-default-config.yml:/etc/wazo-setupd/conf.d/50-default-config.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.5/site-packages/xivo"
    ports:
      - "9302"
